# Generated by Django 5.2.12 on 2026-03-29 08:30

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0034_masterprice_applied_exchange_rate_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('code', models.SlugField(help_text='Уникальный идентификатор, используется в URL и импорте', unique=True, verbose_name='Код')),
                ('sync_method', models.TextField(choices=[('api', 'REST API'), ('ftp', 'FTP/SFTP'), ('email', 'E-mail прайс-лист'), ('manual', 'Вручную')], default='manual', verbose_name='Метод синхронизации')),
                ('api_url', models.TextField(blank=True, verbose_name='URL API')),
                ('api_extra_config', models.JSONField(blank=True, default=dict, help_text='Заголовки, тайм-ауты, маппинг полей и т.д.', verbose_name='Доп. параметры подключения')),
                ('sync_schedule', models.TextField(default='0 6 * * *', help_text='Например: "0 6 * * *" — каждый день в 06:00', verbose_name='Расписание (cron)')),
                ('supplier_is_active', models.BooleanField(default=True, help_text='False — поставщик отключён. Данные сохраняются.', verbose_name='Поставщик активен')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Меньше = выше приоритет при выборе стратегии', verbose_name='Приоритет')),
                ('default_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта по умолчанию')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCatalogSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('pending', 'Ожидает запуска'), ('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частичный успех'), ('failed', 'Ошибка')], default='pending', verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('task_id', models.TextField(blank=True, verbose_name='ID задачи Celery')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Всего позиций')),
                ('created_items', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated_items', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('skipped_items', models.PositiveIntegerField(default=0, verbose_name='Пропущено')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('triggered_by', models.TextField(default='celery', help_text='"celery", "admin", "api" или имя пользователя', verbose_name='Инициатор')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_syncs', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Синхронизация каталога поставщика',
                'verbose_name_plural': 'Синхронизации каталогов поставщиков',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='API-ключ')),
                ('api_secret', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='API-секрет')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Доп. учётные данные')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credential', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Учётные данные поставщика',
                'verbose_name_plural': 'Учётные данные поставщиков',
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.CreateModel(
            name='SupplierStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.TextField(verbose_name='Артикул поставщика')),
                ('price', models.DecimalField(decimal_places=18, max_digits=18, verbose_name='Цена')),
                ('num_in_stock', models.PositiveIntegerField(default=0, verbose_name='На складе')),
                ('num_allocated', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_active', models.BooleanField(default=True, help_text='False — поставщик перестал поставлять этот товар. Данные сохраняются.', verbose_name='Активен')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.product', verbose_name='Товар')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Остаток у поставщика',
                'verbose_name_plural': 'Остатки у поставщиков',
            },
        ),
        migrations.CreateModel(
            name='SupplierStockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_supplier_name', models.TextField(verbose_name='Поставщик (снимок)')),
                ('snapshot_product_title', models.TextField(verbose_name='Товар (снимок)')),
                ('snapshot_product_upc', models.TextField(blank=True, verbose_name='Артикул товара (снимок)')),
                ('snapshot_supplier_sku', models.TextField(blank=True, verbose_name='Артикул поставщика (снимок)')),
                ('snapshot_currency_code', models.TextField(verbose_name='Код валюты (снимок)')),
                ('price_before', models.DecimalField(blank=True, decimal_places=18, max_digits=18, null=True, verbose_name='Цена до')),
                ('price_after', models.DecimalField(decimal_places=18, max_digits=18, verbose_name='Цена после')),
                ('num_in_stock_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток до')),
                ('num_in_stock_after', models.PositiveIntegerField(verbose_name='Остаток после')),
                ('change_type', models.TextField(choices=[('created', 'Создана'), ('price_changed', 'Изменена цена'), ('stock_changed', 'Изменён остаток'), ('both_changed', 'Изменены цена и остаток'), ('deactivated', 'Деактивирован')], db_index=True, verbose_name='Тип изменения')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время записи')),
                ('sync', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suppliers.suppliercatalogsync', verbose_name='Синхронизация-источник')),
                ('stock_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='suppliers.supplierstockrecord', verbose_name='Запись остатка')),
            ],
            options={
                'verbose_name': 'История остатка поставщика',
                'verbose_name_plural': 'История остатков поставщиков',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='suppliercatalogsync',
            index=models.Index(fields=['supplier', '-started_at'], name='suppliers_s_supplie_568501_idx'),
        ),
        migrations.AddIndex(
            model_name='suppliercatalogsync',
            index=models.Index(fields=['status'], name='suppliers_s_status_d78e62_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstockrecord',
            index=models.Index(fields=['supplier', 'is_active'], name='suppliers_s_supplie_ba7e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstockrecord',
            index=models.Index(fields=['product', 'is_active'], name='suppliers_s_product_79c08f_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstockrecord',
            index=models.Index(fields=['supplier', 'supplier_sku'], name='idx_supplier_sku'),
        ),
        migrations.AddConstraint(
            model_name='supplierstockrecord',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='unique_supplier_product_stock'),
        ),
        migrations.AddIndex(
            model_name='supplierstockhistory',
            index=models.Index(fields=['stock_record', '-recorded_at'], name='idx_supplier_stock_history'),
        ),
    ]
