# Generated by Django 5.2.12 on 2026-03-29 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_masterprice_source_stock_record_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='price_after',
            field=models.DecimalField(decimal_places=25, max_digits=50, verbose_name='Цена после'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='price_before',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Цена до'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='price',
            field=models.DecimalField(decimal_places=25, max_digits=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_stock_records', to='catalogue.product', verbose_name='Товар'),
        ),
    ]
