# Generated by Django 5.2.12 on 2026-04-04 10:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_masterprice_source_stock_record_and_more'),
        ('core', '0001_initial'),
        ('suppliers', '0002_alter_supplierstockhistory_price_after_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suppliercatalogsync',
            options={'ordering': ['-started_at'], 'verbose_name': 'Синхронизация', 'verbose_name_plural': 'Синхронизации'},
        ),
        migrations.AlterModelOptions(
            name='suppliercredential',
            options={'verbose_name': 'Учетные данные поставщика', 'verbose_name_plural': 'Учетные данные поставщиков'},
        ),
        migrations.AlterModelOptions(
            name='supplierstockhistory',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'История изменений', 'verbose_name_plural': 'История изменений'},
        ),
        migrations.AlterModelOptions(
            name='supplierstockrecord',
            options={'verbose_name': 'Остаток поставщика', 'verbose_name_plural': 'Остатки поставщиков'},
        ),
        migrations.RemoveConstraint(
            model_name='supplierstockrecord',
            name='unique_supplier_product_stock',
        ),
        migrations.RemoveIndex(
            model_name='suppliercatalogsync',
            name='suppliers_s_status_d78e62_idx',
        ),
        migrations.RemoveIndex(
            model_name='supplierstockrecord',
            name='idx_supplier_sku',
        ),
        migrations.RenameIndex(
            model_name='supplierstockhistory',
            new_name='suppliers_s_stock_r_906434_idx',
            old_name='idx_supplier_stock_history',
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='suppliercredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplierstockrecord',
            name='last_supplier_updated_at',
            field=models.DateTimeField(blank=True, help_text='Если incoming.updated_at <= record.updated_at, обновление пропускается.', null=True, verbose_name='Время обновления у поставщика'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_extra_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. конфигурация API'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='api_url',
            field=models.TextField(blank=True, default='', verbose_name='URL API'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='code',
            field=models.TextField(db_index=True, help_text='Уникальный идентификатор (slug)', unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='default_suppliers', to='core.currency', verbose_name='Валюта по умолчанию'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='priority',
            field=models.PositiveIntegerField(default=100, help_text='Меньше число — выше приоритет', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sync_method',
            field=models.TextField(choices=[('api', 'REST API'), ('manual', 'Ручная загрузка'), ('ftp', 'FTP/SFTP')], default='manual', verbose_name='Метод синхронизации'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='sync_schedule',
            field=models.TextField(default='0 6 * * *', verbose_name='Расписание синхронизации (cron)'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='error_log',
            field=models.TextField(blank=True, default='', verbose_name='Лог ошибок'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='failed_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибки'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='status',
            field=models.TextField(choices=[('pending', 'Ожидание'), ('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично выполнено'), ('failed', 'Ошибка')], default='pending', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='task_id',
            field=models.TextField(blank=True, default='', help_text='ID асинхронной задачи', verbose_name='Celery Task ID'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='total_items',
            field=models.PositiveIntegerField(default=0, verbose_name='Всего элементов'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='triggered_by',
            field=models.TextField(default='celery', verbose_name='Запущено'),
        ),
        migrations.AlterField(
            model_name='suppliercredential',
            name='api_key',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='suppliercredential',
            name='api_secret',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, verbose_name='API Secret'),
        ),
        migrations.AlterField(
            model_name='suppliercredential',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп. данные'),
        ),
        migrations.AlterField(
            model_name='suppliercredential',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='change_type',
            field=models.TextField(choices=[('created', 'Создано'), ('price', 'Изменение цены'), ('stock', 'Изменение остатка'), ('both', 'Изменение цены и остатка'), ('deactivated', 'Деактивировано')], verbose_name='Тип изменения'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='snapshot_currency_code',
            field=models.TextField(verbose_name='Код валюты'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='snapshot_product_title',
            field=models.TextField(verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='snapshot_product_upc',
            field=models.TextField(blank=True, default='', verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='snapshot_supplier_name',
            field=models.TextField(verbose_name='Название поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='snapshot_supplier_sku',
            field=models.TextField(verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_records', to='suppliers.suppliercatalogsync', verbose_name='Синхронизация'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_records', to='core.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='num_allocated',
            field=models.PositiveIntegerField(default=0, help_text='Количество в активных заказах', verbose_name='Зарезервировано'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='num_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='price',
            field=models.DecimalField(decimal_places=25, default=Decimal('0'), max_digits=50, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='suppliers.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='supplier_sku',
            field=models.TextField(db_index=True, verbose_name='Артикул поставщика'),
        ),
        migrations.AlterField(
            model_name='supplierstockrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='suppliercatalogsync',
            index=models.Index(fields=['status', '-started_at'], name='suppliers_s_status_243f65_idx'),
        ),
        migrations.AddIndex(
            model_name='supplierstockhistory',
            index=models.Index(fields=['snapshot_supplier_name', '-recorded_at'], name='suppliers_s_snapsho_c089ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplierstockrecord',
            constraint=models.UniqueConstraint(fields=('supplier', 'product'), name='unique_supplier_product'),
        ),
    ]
