# Generated by Django 5.2.12 on 2026-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_suppliercatalogsync_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='sync_method',
            field=models.TextField(choices=[('API', 'REST API'), ('MANUAL', 'Ручная загрузка'), ('FTP', 'FTP/SFTP')], default='MANUAL', verbose_name='Метод синхронизации'),
        ),
        migrations.AlterField(
            model_name='suppliercatalogsync',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Ожидание'), ('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('PARTIAL', 'Частично выполнено'), ('FAILED', 'Ошибка')], default='PENDING', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplierstockhistory',
            name='change_type',
            field=models.TextField(choices=[('CREATED', 'Создано'), ('PRICE_CHANGED', 'Изменение цены'), ('STOCK_CHANGED', 'Изменение остатка'), ('BOTH_CHANGED', 'Изменение цены и остатка'), ('DEACTIVATED', 'Деактивировано')], verbose_name='Тип изменения'),
        ),
    ]
