# digital_store/settings.yaml

# ─── Default ──────────────────────────────

default:
  db:
    engine: 'django.db.backends.postgresql'
    host: 'localhost'
    port: 5432
    database: 'digital_store'
    user: 'usersvc_digital_store'
    password: 'usersvc_digital_store_password'

    # PgBouncer
    conn_max_age: 0
    # Psycopg
    options:
      prepare_threshold: 0

  # Django Core
  django:
    debug: true
    allowed_hosts:
      - 'localhost'
      - '127.0.0.1'

    salt_key: 'VERY_SECRET_SALT_KEY'
    secret_key: 'VERY_SECRET_SECRET_KEY'

    # Security
    secure_ssl_redirect: true
    session_cookie_secure: true
    csrf_cookie_secure: true
    use_x_forwarded_host: true
    use_x_forwarded_port: true

    # Localization and modeltranslation
    default_language: 'en'
    language_code: 'en-us'
    languages:
      - ['en', 'English']
      - ['ru', 'Русский']
    time_zone: 'UTC'
    use_i18n: true
    use_tz: true

    # Site
    site_id: 1

    # Static / Media
    static_url: '/static/'
    static_root: 'staticfiles'
    staticfiles_dir: static
    media_url: '/media/'
    media_root: 'media'

  # Oscar
  oscar:
    default_currency: 'USD'
    shop_name: 'Digital Store'

# ─── Test ──────────────────────────────────────────────────────────────────────

tests.local:
  db:
    user: 'test_usersvc_digital_store'
    password: 'test_password'

# ─── Production ────────────────────────────────────────────────────────────────

production.local:
  db:
    host: '{env[DB_HOST]}'
    port: '{env[DB_PORT]}'
    user: '{env[DB_USER]}'
    password: '{env[DB_PASSWORD]}'

  django:
    debug: false
    allowed_hosts: {env[ALLOWED_HOSTS]}

    salt_key: '{env[SALT_KEY]}'
    secret_key: '{env[SECRET_KEY]}'
