# Generated by Django 5.2.12 on 2026-03-29 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.TextField(primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Код валюты')),
                ('currency_type', models.TextField(choices=[('FIAT', 'Фиатная валюта'), ('CRYPTO', 'Криптовалюта')], default='FIAT', verbose_name='Тип валюты')),
                ('name', models.TextField(verbose_name='Название')),
                ('name_en', models.TextField(null=True, verbose_name='Название')),
                ('name_ru', models.TextField(null=True, verbose_name='Название')),
                ('symbol', models.TextField(blank=True, verbose_name='Символ')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='Знаков после запятой')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['currency_type', 'currency_code'],
            },
        ),
    ]
