# Generated by Django 5.2.12 on 2026-03-29 07:39

import django.db.models.deletion
import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True, verbose_name='Название')),
                ('source_type', models.TextField(choices=[('cbr', 'ЦБ РФ'), ('ecb', 'Европейский ЦБ'), ('open_er', 'OpenExchangeRates'), ('fixer', 'Fixer.io'), ('custom_api', 'Кастомный API')], verbose_name='Тип источника')),
                ('api_url', models.TextField(blank=True, verbose_name='URL API')),
                ('api_extra_config', models.JSONField(blank=True, default=dict, help_text='Для CoinCap: {"ids": {"USD": "united-states-dollar", "RUB": "russian-ruble"}}', verbose_name='Доп. конфигурация API')),
                ('sync_schedule', models.TextField(default='0 9 * * 1-5', help_text='"0 9 * * 1-5" — в 09:00 по рабочим дням', verbose_name='Расписание (cron)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='При конфликте используется источник с меньшим значением', verbose_name='Приоритет')),
                ('base_currency', models.ForeignKey(help_text='У ЦБ РФ — RUB, у ECB — EUR', on_delete=django.db.models.deletion.PROTECT, related_name='base_for_sources', to='core.currency', verbose_name='Базовая валюта')),
                ('tracked_currencies', models.ManyToManyField(blank=True, related_name='tracked_by_sources', to='core.currency', verbose_name='Отслеживаемые валюты')),
            ],
            options={
                'verbose_name': 'Источник курсов валют',
                'verbose_name_plural': 'Источники курсов валют',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateSourceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='API-ключ')),
                ('api_secret', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=512, verbose_name='API-секрет')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credential', to='currencies.currencyratesource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Учётные данные источника курсов',
                'verbose_name_plural': 'Учётные данные источников курсов',
                'default_permissions': ('view', 'change'),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=25, help_text='Сколько to_currency за 1 from_currency', max_digits=50, verbose_name='Курс')),
                ('rate_datetime', models.DateTimeField(verbose_name='Дата и время курса')),
                ('updated_at', models.DateTimeField(verbose_name='Обновлён')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_from', to='core.currency', verbose_name='Из валюты')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='currencies.currencyratesource', verbose_name='Источник')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates_to', to='core.currency', verbose_name='В валюту')),
            ],
            options={
                'verbose_name': 'Актуальный курс валют',
                'verbose_name_plural': 'Актуальные курсы валют',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_source_name', models.TextField(verbose_name='Источник (снимок)')),
                ('snapshot_from_currency', models.TextField(verbose_name='Из валюты (снимок)')),
                ('snapshot_to_currency', models.TextField(verbose_name='В валюту (снимок)')),
                ('rate', models.DecimalField(decimal_places=25, max_digits=50, verbose_name='Курс')),
                ('rate_datetime', models.DateTimeField(verbose_name='Дата и время курса')),
                ('previous_rate', models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Предыдущий курс')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время записи')),
                ('rate_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='currencies.exchangerate', verbose_name='Запись курса')),
            ],
            options={
                'verbose_name': 'История курсов валют',
                'verbose_name_plural': 'История курсов валют',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyRateSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('failed', 'Ошибка')], default='pending', verbose_name='Статус')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('task_id', models.TextField(blank=True, verbose_name='ID задачи Celery')),
                ('rates_updated', models.PositiveIntegerField(default=0, verbose_name='Курсов обновлено')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syncs', to='currencies.currencyratesource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Синхронизация курсов',
                'verbose_name_plural': 'Синхронизации курсов',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='idx_currency_sync_source')],
            },
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['from_currency', 'to_currency'], name='idx_currency_pair'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.UniqueConstraint(fields=('source', 'from_currency', 'to_currency'), name='unique_rate_per_source'),
        ),
        migrations.AddConstraint(
            model_name='exchangerate',
            constraint=models.CheckConstraint(condition=models.Q(('from_currency', models.F('to_currency')), _negated=True), name='exchange_rate_different_currencies'),
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['snapshot_from_currency', 'snapshot_to_currency', '-rate_datetime'], name='idx_rate_history_pair_date'),
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['snapshot_source_name', '-recorded_at'], name='idx_rate_history_source'),
        ),
    ]
