# Generated by Django 5.2.12 on 2026-04-04 10:51

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyratesourcecredential',
            name='api_key',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, verbose_name='API Key'),
        ),
        migrations.AlterField(
            model_name='currencyratesourcecredential',
            name='api_secret',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, verbose_name='API Secret'),
        ),
    ]
