# Generated by Django 5.2.12 on 2026-03-23 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exchangeratehistory',
            name='idx_rate_history_pair_date',
        ),
        migrations.RemoveField(
            model_name='exchangerate',
            name='rate_date',
        ),
        migrations.RemoveField(
            model_name='exchangeratehistory',
            name='rate_date',
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='rate_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время курса'),
        ),
        migrations.AddField(
            model_name='exchangeratehistory',
            name='rate_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время курса'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='updated_at',
            field=models.DateTimeField(verbose_name='Обновлён'),
        ),
        migrations.AddIndex(
            model_name='exchangeratehistory',
            index=models.Index(fields=['snapshot_from_currency', 'snapshot_to_currency', '-rate_datetime'], name='idx_rate_history_pair_date'),
        ),
    ]
