# Generated by Django 5.2.12 on 2026-03-23 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_remove_exchangeratehistory_idx_rate_history_pair_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate_datetime',
            field=models.DateTimeField(verbose_name='Дата и время курса'),
        ),
        migrations.AlterField(
            model_name='exchangeratehistory',
            name='rate_datetime',
            field=models.DateTimeField(verbose_name='Дата и время курса'),
        ),
    ]
