# Generated by Django 5.2.12 on 2026-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0002_alter_currencyratesourcecredential_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyratesource',
            name='source_type',
            field=models.TextField(choices=[('CBR', 'ЦБ РФ'), ('ECB', 'Европейский ЦБ'), ('OPEN_ER', 'OpenExchangeRates'), ('FIXER', 'Fixer.io'), ('CUSTOM_API', 'Кастомный API')], verbose_name='Тип источника'),
        ),
        migrations.AlterField(
            model_name='currencyratesync',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Ожидает'), ('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('FAILED', 'Ошибка')], default='PENDING', verbose_name='Статус'),
        ),
    ]
