# Generated by Django 5.2.12 on 2026-03-25 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0003_alter_exchangerate_rate_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyratesource',
            name='api_extra_config',
            field=models.JSONField(blank=True, default=dict, help_text='Для CoinCap: {"ids": {"USD": "united-states-dollar", "RUB": "russian-ruble"}}', verbose_name='Доп. конфигурация API'),
        ),
    ]
