# Generated by Django 5.2.12 on 2026-03-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0004_currencyratesource_api_extra_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=25, help_text='Сколько to_currency за 1 from_currency', max_digits=50, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='exchangeratehistory',
            name='previous_rate',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Предыдущий курс'),
        ),
        migrations.AlterField(
            model_name='exchangeratehistory',
            name='rate',
            field=models.DecimalField(decimal_places=25, max_digits=50, verbose_name='Курс'),
        ),
    ]
