# Generated by Django 5.2.12 on 2026-03-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0032_category_exclude_from_menu_category_long_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterCatalogSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(choices=[('pending', 'Ожидает'), ('running', 'Выполняется'), ('success', 'Успешно'), ('partial', 'Частично'), ('failed', 'Ошибка')], default='pending', verbose_name='Статус')),
                ('sync_source', models.TextField(choices=[('manual', 'Вручную'), ('import', 'Импорт файла'), ('api', 'Внешний API'), ('celery', 'Планировщик')], default='celery', verbose_name='Источник синхронизации')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец')),
                ('task_id', models.TextField(blank=True, verbose_name='ID задачи Celery')),
                ('triggered_by', models.TextField(blank=True, verbose_name='Инициатор')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='Всего')),
                ('created_items', models.PositiveIntegerField(default=0, verbose_name='Создано')),
                ('updated_items', models.PositiveIntegerField(default=0, verbose_name='Обновлено')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
            ],
            options={
                'verbose_name': 'Синхронизация основного каталога',
                'verbose_name_plural': 'Синхронизации основного каталога',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=18, max_digits=18, verbose_name='Цена')),
                ('applied_rate_value', models.DecimalField(decimal_places=18, help_text='Денормализованный снимок — не меняется при обновлении курса', max_digits=18, verbose_name='Значение курса на момент пересчёта')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Витринная цена',
                'verbose_name_plural': 'Витринные цены',
            },
        ),
        migrations.CreateModel(
            name='MasterPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_before', models.DecimalField(blank=True, decimal_places=18, max_digits=18, null=True, verbose_name='Цена до')),
                ('price_after', models.DecimalField(decimal_places=18, max_digits=18, verbose_name='Цена после')),
                ('change_reason', models.TextField(choices=[('created', 'Создана'), ('supplier_price', 'Изменилась цена поставщика'), ('exchange_rate', 'Изменился курс валют'), ('supplier_changed', 'Смена поставщика-источника'), ('manual', 'Ручное изменение')], db_index=True, verbose_name='Причина изменения')),
                ('snapshot_product_title', models.TextField(verbose_name='Товар (снимок)')),
                ('snapshot_currency_code', models.TextField(verbose_name='Код валюты (снимок)')),
                ('snapshot_supplier_name', models.TextField(blank=True, verbose_name='Поставщик (снимок)')),
                ('snapshot_supplier_price', models.DecimalField(blank=True, decimal_places=18, max_digits=18, null=True, verbose_name='Цена поставщика (снимок)')),
                ('snapshot_source_currency', models.TextField(blank=True, verbose_name='Валюта поставщика (снимок)')),
                ('snapshot_applied_rate', models.DecimalField(blank=True, decimal_places=18, max_digits=18, null=True, verbose_name='Курс на момент изменения (снимок)')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время записи')),
            ],
            options={
                'verbose_name': 'История витринной цены',
                'verbose_name_plural': 'История витринных цен',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_in_stock', models.PositiveIntegerField(default=0, verbose_name='На складе (итого)')),
                ('num_allocated', models.PositiveIntegerField(default=0, verbose_name='Зарезервировано (итого)')),
                ('suppliers_count', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во активных поставщиков')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Основной остаток',
                'verbose_name_plural': 'Основные остатки',
            },
        ),
    ]
