# Generated by Django 5.2.12 on 2026-03-29 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_mastercatalogsync_masterprice_masterpricehistory_and_more'),
        ('core', '0001_initial'),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprice',
            name='applied_exchange_rate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='currencies.exchangeratehistory', verbose_name='Применённый курс (FK)'),
        ),
        migrations.AddField(
            model_name='masterprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='masterprice',
            name='last_sync',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogue.mastercatalogsync', verbose_name='Последняя синхронизация'),
        ),
        migrations.AddField(
            model_name='masterprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='master_prices', to='catalogue.product', verbose_name='Товар'),
        ),
    ]
