# Generated by Django 5.2.12 on 2026-03-29 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0033_mastercatalogsync_masterprice_masterpricehistory_and_more'),
        ('core', '0001_initial'),
        ('currencies', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprice',
            name='applied_exchange_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='currencies.exchangerate', verbose_name='Применённый курс (FK)'),
        ),
        migrations.AddField(
            model_name='masterprice',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='master_prices', to='core.currency', verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterprice',
            name='last_sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.mastercatalogsync', verbose_name='Последняя синхронизация'),
        ),
        migrations.AddField(
            model_name='masterprice',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='master_prices', to='catalogue.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterprice',
            name='source_stock_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_as_master_price', to='suppliers.supplierstockrecord', verbose_name='Источник цены (поставщик)'),
        ),
        migrations.AddField(
            model_name='masterpricehistory',
            name='master_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='history', to='catalogue.masterprice', verbose_name='Витринная цена'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterpricehistory',
            name='sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.mastercatalogsync', verbose_name='Синхронизация'),
        ),
        migrations.AddField(
            model_name='masterstockrecord',
            name='last_sync',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.mastercatalogsync', verbose_name='Последняя синхронизация'),
        ),
        migrations.AddField(
            model_name='masterstockrecord',
            name='product',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='master_stock', to='catalogue.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='masterpricehistory',
            index=models.Index(fields=['master_price', '-recorded_at'], name='idx_master_price_history'),
        ),
        migrations.AddConstraint(
            model_name='masterprice',
            constraint=models.UniqueConstraint(fields=('product', 'currency'), name='unique_master_price_product_currency'),
        ),
    ]
