# Generated by Django 5.2.12 on 2026-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0035_masterprice_source_stock_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercatalogsync',
            name='status',
            field=models.TextField(choices=[('PENDING', 'Ожидает'), ('RUNNING', 'Выполняется'), ('SUCCESS', 'Успешно'), ('PARTIAL', 'Частично'), ('FAILED', 'Ошибка')], default='PENDING', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='mastercatalogsync',
            name='sync_source',
            field=models.TextField(choices=[('MANUAL', 'Вручную'), ('IMPORT', 'Импорт файла'), ('API', 'Внешний API'), ('CELERY', 'Планировщик')], default='CELERY', verbose_name='Источник синхронизации'),
        ),
        migrations.AlterField(
            model_name='masterprice',
            name='applied_rate_value',
            field=models.DecimalField(decimal_places=25, help_text='Денормализованный снимок — не меняется при обновлении курса', max_digits=50, verbose_name='Значение курса на момент пересчёта'),
        ),
        migrations.AlterField(
            model_name='masterprice',
            name='price',
            field=models.DecimalField(decimal_places=25, max_digits=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='masterpricehistory',
            name='change_reason',
            field=models.TextField(choices=[('CREATED', 'Создана'), ('SUPPLIER_PRICE', 'Изменилась цена поставщика'), ('EXCHANGE_RATE', 'Изменился курс валют'), ('SUPPLIER_CHANGED', 'Смена поставщика-источника'), ('MANUAL', 'Ручное изменение')], db_index=True, verbose_name='Причина изменения'),
        ),
        migrations.AlterField(
            model_name='masterpricehistory',
            name='price_after',
            field=models.DecimalField(decimal_places=25, max_digits=50, verbose_name='Цена после'),
        ),
        migrations.AlterField(
            model_name='masterpricehistory',
            name='price_before',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Цена до'),
        ),
        migrations.AlterField(
            model_name='masterpricehistory',
            name='snapshot_applied_rate',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Курс на момент изменения (снимок)'),
        ),
        migrations.AlterField(
            model_name='masterpricehistory',
            name='snapshot_supplier_price',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Цена поставщика (снимок)'),
        ),
    ]
